services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "${PORT}:${PORT}"
    environment:
      YARN_CACHE_FOLDER: /app/.yarn-cache
      YARN_RC_FILE: /app/.yarnrc
      NODE_ENV: ${NODE_ENV}
      DEBUG: ${DEBUG}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_URI: ${MONGO_URI}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PORT: ${PORT}
    image: backend-tavola-italiana:v1.0.0
    volumes:
      - ./data:/app/data:rw
      - ./logs:/var/log:rw
    networks:
      - app-network
    depends_on:
      - postgres
      - mongo
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  fluent-bit:
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluent-bit.conf:/fluent-bit.conf:ro
      - ./fluent-bit-config:/fluent-bit/etc:ro
      - ./logs:/var/log:rw
    environment:
      - FLUENTBIT_CONF=/fluent-bit.conf:ro
      - FLUENTBIT_LOG_LEVEL=debug
    ports:
      - "24224:24224"

networks:
  app-network:
    driver: bridge

volumes:
  encrypted_data:
    driver: local
    driver_opts:
      type: "ext4"
      o: "encrypt"
  postgres_data:
  mongo_data:
