version: "3.8"

services:
  backend:
    fluent-bit:
      image: fluent/fluent-bit:latest
      volumes:
        - ./fluent-bit.conf:/fluent-bit.conf
      environment:
        - FLUENTBIT_CONF=/fluent-bit.conf
      ports:
        - "24224:24224"
    build:
      context: .
      dockerfile: Dockerfile
      user: "1001:1001" # Replace with actual user and group IDs
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    # image: node:22-alpine # I already have on the Dockerfile
    image: backend-tavola-italiana:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MONGO_URI: ${MONGO_URI}
    volumes:
      - ./data:/app/data:ro
    networks:
      - app-network
    depends_on:
      - postgres
      - mongo
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  encrypted_data:
    driver: local
    driver_opts:
      type: "ext4"
      o: "encrypt"
  postgres_data:
  mongo_data:
