services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # Resolve this later(This is interfering with the ProductController image upload feature.)
    # cap_drop:
    #   - ALL
    # cap_add:
    #   - NET_BIND_SERVICE
    ports:
      - "${PORT}:${PORT}"
    environment:
      YARN_CACHE_FOLDER: /app/.yarn-cache
      YARN_RC_FILE: /app/.yarnrc
      NODE_ENV: ${NODE_ENV}
      DEBUG: ${DEBUG}
      JWT_SECRET: ${JWT_SECRET}
      FLUENTBIT_PORT: ${FLUENTBIT_PORT}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_URI: ${MONGO_URI}
      MONGO_USER: ${MONGO_USER}
      MONGO_DB: ${MONGO_DB}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PORT: ${PORT}
    image: backend-tavola-italiana:v1.0.0
    container_name: backend
    networks:
      - app_network
    volumes:
      - ./data:/app/data:rw
      - ./logs:/var/log:rw
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
      # Resolve this later(It's getting in the way of the backend going up)
      # fluent-bit:
      #   condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:${PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:4

    container_name: mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5


  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    networks:
      - app_network
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluent-bit-config:/fluent-bit/etc:rw
      - ./logs:/var/log:rw
    environment:
      FLUENTBIT_CONF: /fluent-bit/etc/fluent-bit.conf
      FLUENTBIT_LOG_LEVEL: info
    ports:
      - "${FLUENTBIT_PORT}:${FLUENTBIT_PORT}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:2020/api/v1/metrics"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
  encrypted_data:
    driver: local
    driver_opts:
      type: "ext4"
      o: "encrypt"
  postgres_data:
  mongo_data:
  fluent-bit:
  app:
